# Intercom Settings Addon

esphome:
  on_boot:
    then:
      - if:
          condition:
             - lambda: return id(serial_number).state != 0 && id(intercom_model).state != "None";
          then:
            - tc_bus.read_memory:

# Extend TC:BUS Component
tc_bus:
  on_read_memory_complete:
    - lambda: |-
        std::string hexString = str_upper_case(format_hex(x));
        ESP_LOGI("tcs_bus", "Memory reading completed. Data: %s", hexString.c_str());

  on_read_memory_timeout:
    - logger.log:
        format: "Memory reading timed out! No memory block received in time."
        level: ERROR

  on_identify_complete:
    - logger.log:
        format: "Identified Hardware: %s (v%i) | Firmware: %i.%i.%i"
        args: [ 'model_to_string(x.model)', 'x.hardware_version', 'x.firmware_major', 'x.firmware_minor', 'x.firmware_patch' ]
        level: INFO
    - delay: 2s
    - tc_bus.read_memory:

  on_identify_timeout:
    - logger.log:
        format: "Failed to identify the Indoor Station. Please select it manually."
        level: ERROR

select:
  - platform: tc_bus
    model:
      id: intercom_model
      name: "Intercom Model"
      icon: "mdi:doorbell-video"
      entity_category: CONFIG
      disabled_by_default: true
      web_server:
        sorting_group_id: sorting_group_intercom_settings
        sorting_weight: -97
        
    ringtone_entrance_door_call:
      id: intercom_ringtone_entrance_door_call
      name: "Ringtone: Entrance Door Call"
      icon: "mdi:music"
      entity_category: CONFIG
      disabled_by_default: true
      web_server:
        sorting_group_id: sorting_group_intercom_settings
        sorting_weight: -80

    ringtone_second_entrance_door_call:
      id: intercom_ringtone_second_entrance_door_call
      name: "Ringtone: Second Entrance Door Call"
      icon: "mdi:music"
      entity_category: CONFIG
      disabled_by_default: true
      web_server:
        sorting_group_id: sorting_group_intercom_settings
        sorting_weight: -79

    ringtone_floor_call:
      id: intercom_ringtone_floor_call
      name: "Ringtone: Floor Call"
      icon: "mdi:music"
      entity_category: CONFIG
      disabled_by_default: true
      web_server:
        sorting_group_id: sorting_group_intercom_settings
        sorting_weight: -78

    ringtone_internal_call:
      id: intercom_ringtone_internal_call
      name: "Ringtone: Internal Call"
      icon: "mdi:music"
      entity_category: CONFIG
      disabled_by_default: true
      web_server:
        sorting_group_id: sorting_group_intercom_settings
        sorting_weight: -77

number:
  - platform: tc_bus
    volume_ringtone:
      id: intercom_volume_ringtone
      name: "Volume: Ringtone"
      icon: "mdi:volume-high"
      entity_category: CONFIG
      disabled_by_default: true
      web_server:
        sorting_group_id: sorting_group_intercom_settings
        sorting_weight: -70

    volume_handset_door_call:
      id: intercom_volume_handset_door_call
      name: "Volume: Handset Door Call"
      icon: "mdi:volume-high"
      entity_category: CONFIG
      disabled_by_default: true
      web_server:
        sorting_group_id: sorting_group_intercom_settings
        sorting_weight: -69

    volume_handset_internal_call:
      id: intercom_volume_handset_internal_call
      name: "Volume: Handset Internal Call"
      icon: "mdi:volume-high"
      entity_category: CONFIG
      disabled_by_default: true
      web_server:
        sorting_group_id: sorting_group_intercom_settings
        sorting_weight: -68
      
# Read Memory before reading and writing
button:
  - platform: template
    id: read_memory
    name: "Read Memory"
    icon: "mdi:file-arrow-up-down"
    on_press:
      - tc_bus.read_memory:
    entity_category: CONFIG
    disabled_by_default: true
    web_server:
      sorting_group_id: sorting_group_intercom_settings
      sorting_weight: -95

  - platform: template
    id: identify_indoor_station
    name: "Identify Indoor Station"
    icon: "mdi:identifier"
    entity_category: CONFIG
    disabled_by_default: true
    on_press:
      - tc_bus.identify:
    web_server:
      sorting_group_id: sorting_group_intercom_settings
      sorting_weight: -96
