# OTA Updates Addon -  ESPHome

ota:
  - platform: esphome
    id: ota_esphome

  - platform: web_server
    id: ota_webserver

button:
  - platform: safe_mode
    id: doorman_safe_mode
    name: Safe mode
    entity_category: CONFIG
    disabled_by_default: true
    web_server:
      sorting_group_id: sorting_group_system
      sorting_weight: 11