name: Build Vitepress Docs

on:
  workflow_call:

jobs:
  build-docs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm
          cache-dependency-path: docs/package-lock.json

      - name: Setup Pages
        uses: actions/configure-pages@v4

      - name: Extract version and prepare environment
        run: |
          VERSION=$(awk '/project:/, /version:/' firmware/base.yaml | grep 'version:' | awk '{print $2}' | sed 's/[",]//g')
          
          if [[ "${{ github.ref_name }}" == dev* ]]; then
            TIMESTAMP=$(date +%d%H%M)
            echo "FULL_VERSION=${VERSION}-dev.${TIMESTAMP}" >> $GITHUB_ENV
          else
            echo "FULL_VERSION=${VERSION}" >> $GITHUB_ENV
          fi

      - name: Update package.json version
        working-directory: docs
        run: |
          sed -i "s/\"version\": \".*\"/\"version\": \"${FULL_VERSION}\"/" package.json
          
      - name: Update example firmware branch references
        if: startsWith(github.ref_name, 'dev')
        working-directory: firmware/examples
        run: |
          sed -i "s/master.yaml@master/dev.yaml@${{ github.ref_name }}/g" *.example.yaml

      - name: Update documentation branch references
        if: startsWith(github.ref_name, 'dev')
        working-directory: docs
        run: |
          # Update 3D printing guide
          sed -i "s/master/${{ github.ref_name }}/g" */guide/enclosure/3d-printing.md
          
          # Update schematics references
          sed -i "s/@master/@${{ github.ref_name }}/g" */reference/schematics.md

          # Update example references
          sed -i "s/@master/@${{ github.ref_name }}/g" */guide/firmware/customization.md
          sed -i "s/branch: \"master\"/branch: \"${{ github.ref_name }}\"/g" */guide/firmware/customization.md
          
          # Update firmware example references
          sed -i "s/master.yaml@master/dev.yaml@${{ github.ref_name }}/g" */guide/firmware/minimal.example.yaml
          
          # Update ESPHome component references
          sed -i "s/@master/@${{ github.ref_name }}/g" */reference/esphome-component*.md

      - name: Install dependencies
        working-directory: docs
        run: npm ci

      - name: Build with VitePress
        working-directory: docs
        run: npm run build

      - name: Build Lunaria Dashboard
        working-directory: docs
        run: npm run lunaria:build

      - name: Upload VitePress artifact
        uses: actions/upload-artifact@v4
        with:
          name: vitepress-docs
          path: docs/.vitepress/dist