name: Build and Publish ESPHome firmware

on:
  workflow_call:
    inputs:
      files:
        description: Comma-separated list of files to build.
        required: true
        type: string
      name:
        description: Name of the firmware to publish.
        required: false
        type: string
        default: ESPHome
      esphome_version:
        description: Version of ESPHome to build for.
        required: false
        type: string
        default: latest
      directory_name:
        description: Name of the output folder
        required: true
        type: string
        default: esp32
      summary:
        description: Summary of the release
        required: false
        type: string
        default: Not available
      url:
        description: URL of the release
        required: false
        type: string
        default: "https://github.com/azoninc/doorman/releases"

jobs:
  prepare:
    name: Prepare
    runs-on: ubuntu-latest
    outputs:
      files: ${{ steps.files-array.outputs.files }}
    steps:
      - id: files-array
        run: |
          files=$(echo "${{ inputs.files }}" | jq -Rcn 'inputs | . / ","')
          echo "files=$files" >> $GITHUB_OUTPUT

  build:
    name: Build ${{ matrix.file }}
    needs: [prepare]
    runs-on: ubuntu-latest
    strategy:
      matrix:
        file: ${{ fromJson(needs.prepare.outputs.files) }}
    outputs:
      esphome-version: ${{ steps.esphome-build.outputs.version }}
      esphome-build-name: ${{ steps.esphome-build.outputs.name}}
      project-version: ${{ steps.esphome-build.outputs.project-version }}
    steps:
      - uses: actions/checkout@v5
      
      - name: Update version for dev builds
        if: startsWith(github.ref_name, 'dev')
        run: |
          VERSION=$(awk '/project:/, /version:/' firmware/base.yaml | grep 'version:' | awk '{print $2}' | sed 's/[",]//g')
          TIMESTAMP=$(date +%d%H%M)
          DEV_VERSION="${VERSION}-dev.${TIMESTAMP}"
          sed -i "/^  project:/,/^  platformio_options:/s/^    version: .*/    version: \"${DEV_VERSION}\"/" firmware/base.yaml

      - name: Build ESPHome firmware
        uses: esphome/build-action@v7.1.0
        id: esphome-build
        with:
          yaml-file: ${{ matrix.file }}
          version: ${{ inputs.esphome_version }}
          release-url: ${{ inputs.url }}
          release-summary: ${{ inputs.summary }}
          complete-manifest: true

      - name: Prepare output directory
        run: |
          mkdir -p output
          mv "${{ steps.esphome-build.outputs.name}}" "output/${{ inputs.directory_name }}"

      - name: Update manifest
        run: |
          MANIFEST="output/${{ inputs.directory_name }}/manifest.json"

          # Update JSON values with jq
          jq '.new_install_prompt_erase = true |
              .name = "${{ inputs.name }}" |
              .funding_url = "https://github.com/sponsors/AzonInc"' \
            "$MANIFEST" > "${MANIFEST}.tmp" && mv "${MANIFEST}.tmp" "$MANIFEST"
    
      - name: Upload firmware artifact
        uses: actions/upload-artifact@v5
        with:
          name: firmware.${{ inputs.directory_name }}
          path: output