name: Bundle build assets

on:
  workflow_call:

jobs:
  bundle-assets:
    name: Create asset bundle
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Create Output Directories
        run: |
          mkdir -p output/firmware/release
          mkdir -p output/firmware/temp

      - name: Download VitePress docs
        uses: actions/download-artifact@v4
        with:
          name: vitepress-docs
          path: output

      - name: Copy interactive BOM
        run: cp pcb/bom/ibom.html output/
        
      - name: Download all firmware artifacts
        uses: actions/download-artifact@v4
        with:
          pattern: firmware.*
          path: output/firmware/release
          merge-multiple: true

      - name: Upload Pages artifact
        if: github.ref_name == 'master'
        uses: actions/upload-pages-artifact@v3
        with:
          path: output
      
      - name: Upload Assets Bundle
        if: startsWith(github.ref_name, 'dev')
        uses: actions/upload-artifact@v4
        with:
          name: asset-bundle
          path: output