name: Bundle build assets

on:
  workflow_call:

jobs:
  bundle-assets:
    name: Create asset bundle
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Create Output Directory
        run: mkdir -p output 

      - name: Create Fimrware Directory
        run: mkdir -p output/firmware/release/

      - name: Create Temp Directory
        run: mkdir -p output/firmware/temp/

      - name: Download github-pages artifact
        uses: actions/download-artifact@v4
        with:
          name: vitepress-docs
          path: output

      - name: Copy interactive BOM
        run: cp pcb/bom/ibom.html output/
        

      # Stock Firmware - ESP32
      - name: Download Doorman Stock for Home Assistant (ESP32,HA) artifact
        uses: actions/download-artifact@v4
        with:
          name: firmware.esp32.ha.stock
          path: output/firmware/release

      - name: Download Doorman Stock for Home Assistant (ESP32, MQTT) artifact
        uses: actions/download-artifact@v4
        with:
          name: firmware.esp32.mqtt.stock
          path: output/firmware/release
      - name: Download Doorman Stock for Home Assistant (ESP32, HomeKit) artifact
        uses: actions/download-artifact@v4
        with:
          name: firmware.esp32.homekit.stock
          path: output/firmware/release
      - name: Download Doorman Stock for Home Assistant (ESP32, Custom) artifact
        uses: actions/download-artifact@v4
        with:
          name: firmware.esp32.custom.stock
          path: output/firmware/release

      # Stock Firmware - ESP32-S3
      - name: Download Doorman Stock for Home Assistant (ESP32-S3, HA) artifact
        uses: actions/download-artifact@v4
        with:
          name: firmware.esp32-s3.ha.stock
          path: output/firmware/release
      - name: Download Doorman Stock for Home Assistant (ESP32-S3, MQTT) artifact
        uses: actions/download-artifact@v4
        with:
          name: firmware.esp32-s3.mqtt.stock
          path: output/firmware/release
      - name: Download Doorman Stock for Home Assistant (ESP32-S3, HomeKit) artifact
        uses: actions/download-artifact@v4
        with:
          name: firmware.esp32-s3.homekit.stock
          path: output/firmware/release
      - name: Download Doorman Stock for Home Assistant (ESP32-S3, Custom) artifact
        uses: actions/download-artifact@v4
        with:
          name: firmware.esp32-s3.custom.stock
          path: output/firmware/release

      # Stock Firmware - ESP32-S3-Quad
      - name: Download Doorman Stock for Home Assistant (ESP32-S3-Quad, HA) artifact
        uses: actions/download-artifact@v4
        with:
          name: firmware.esp32-s3-quad.ha.stock
          path: output/firmware/release
      - name: Download Doorman Stock for Home Assistant (ESP32-S3-Quad, MQTT) artifact
        uses: actions/download-artifact@v4
        with:
          name: firmware.esp32-s3-quad.mqtt.stock
          path: output/firmware/release
      - name: Download Doorman Stock for Home Assistant (ESP32-S3-Quad, HomeKit) artifact
        uses: actions/download-artifact@v4
        with:
          name: firmware.esp32-s3-quad.homekit.stock
          path: output/firmware/release
      - name: Download Doorman Stock for Home Assistant (ESP32-S3-Quad, Custom) artifact
        uses: actions/download-artifact@v4
        with:
          name: firmware.esp32-s3-quad.custom.stock
          path: output/firmware/release


      # Nuki-Bridge Firmware - ESP32
      - name: Download Doorman Nuki Bridge for Home Assistant (ESP32, HA) artifact
        uses: actions/download-artifact@v4
        with:
          name: firmware.esp32.ha.nuki-bridge
          path: output/firmware/release
      #- name: Download Doorman Nuki Bridge for Home Assistant (ESP32, MQTT) artifact
      #  uses: actions/download-artifact@v4
      #  with:
      #    name: firmware.esp32.mqtt.nuki-bridge
      #    path: output/firmware/release
      #- name: Download Doorman Nuki Bridge for Home Assistant (ESP32, HomeKit) artifact
      #  uses: actions/download-artifact@v4
      #  with:
      #    name: firmware.esp32.homekit.nuki-bridge
      #    path: output/firmware/release
      - name: Download Doorman Nuki Bridge for Home Assistant (ESP32, Custom) artifact
        uses: actions/download-artifact@v4
        with:
          name: firmware.esp32.custom.nuki-bridge
          path: output/firmware/release

      # Nuki-Bridge Firmware - ESP32-S3
      - name: Download Doorman Nuki Bridge for Home Assistant (ESP32-S3, HA) artifact
        uses: actions/download-artifact@v4
        with:
          name: firmware.esp32-s3.ha.nuki-bridge
          path: output/firmware/release
      #- name: Download Doorman Nuki Bridge for Home Assistant (ESP32-S3, MQTT) artifact
      #  uses: actions/download-artifact@v4
      #  with:
      #    name: firmware.esp32-s3.mqtt.nuki-bridge
      #    path: output/firmware/release
      #- name: Download Doorman Nuki Bridge for Home Assistant (ESP32-S3, HomeKit) artifact
      #  uses: actions/download-artifact@v4
      #  with:
      #    name: firmware.esp32-s3.homekit.nuki-bridge
      #    path: output/firmware/release
      - name: Download Doorman Nuki Bridge for Home Assistant (ESP32-S3, Custom) artifact
        uses: actions/download-artifact@v4
        with:
          name: firmware.esp32-s3.custom.nuki-bridge
          path: output/firmware/release

      # Nuki-Bridge Firmware - ESP32-S3-Quad
      - name: Download Doorman Nuki Bridge for Home Assistant (ESP32-S3-Quad, HA) artifact
        uses: actions/download-artifact@v4
        with:
          name: firmware.esp32-s3-quad.ha.nuki-bridge
          path: output/firmware/release
      #- name: Download Doorman Nuki Bridge for Home Assistant (ESP32-S3-Quad, MQTT) artifact
      #  uses: actions/download-artifact@v4
      #  with:
      #    name: firmware.esp32-s3-quad.mqtt.nuki-bridge
      #    path: output/firmware/release
      #- name: Download Doorman Nuki Bridge for Home Assistant (ESP32-S3-Quad, HomeKit) artifact
      #  uses: actions/download-artifact@v4
      #  with:
      #    name: firmware.esp32-s3-quad.homekit.nuki-bridge
      #    path: output/firmware/release
      - name: Download Doorman Nuki Bridge for Home Assistant (ESP32-S3-Quad, Custom) artifact
        uses: actions/download-artifact@v4
        with:
          name: firmware.esp32-s3-quad.custom.nuki-bridge
          path: output/firmware/release


      - name: Upload Pages artifact
        if: github.ref_name == 'master'
        uses: actions/upload-pages-artifact@v3
        with:
          path: output
      
      - name: Upload Assets Bundle
        if: startsWith(github.ref_name, 'dev')
        uses: actions/upload-artifact@v4
        with:
          name: asset-bundle
          path: output