name: Bundle build assets

on:
  workflow_call:

jobs:
  bundle-assets:
    name: Create asset bundle
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Create Output Directories
        run: |
          mkdir -p output/firmware/release
          mkdir -p output/firmware/temp

      - name: Download VitePress docs
        uses: actions/download-artifact@v6
        with:
          name: vitepress-docs
          path: output

      - name: Copy interactive BOM
        run: cp pcb/bom/ibom.html output/

      - name: Download Webserver Bundle
        uses: actions/download-artifact@v6
        with:
          name: webserver-bundle
          path: output/firmware/esphome-webserver
        
      - name: Download all firmware artifacts
        uses: actions/download-artifact@v6
        with:
          pattern: firmware.*
          path: output/firmware/release
          merge-multiple: true

      # Temporary duplicate for stock compatibility
      - name: Temporary backwards compatibility for stock firmware filenames
        working-directory: output/firmware/release
        run: |
          for f in *.standard; do cp -r "$f" "${f%.standard}.stock"; done

      - name: Upload Pages artifact
        if: github.ref_name == 'master'
        uses: actions/upload-pages-artifact@v4
        with:
          path: output
      
      - name: Upload Assets Bundle
        if: startsWith(github.ref_name, 'dev')
        uses: actions/upload-artifact@v5
        with:
          name: asset-bundle
          path: output